# -*- coding: utf-8 -*-
"""ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_jyDN4yPt3t1XVZenuxkMJDoH-zvDTrX
"""

import numpy as np
from sklearn.linear_model import LinearRegression

# Base de dados
dados = [
    {"ID": 1, "Produto": "Tinta Acrílica", "Ano": 2023, "Mês": 1, "Trimestre": 1, "Vendas": 120},
    {"ID": 2, "Produto": "Tinta Acrílica", "Ano": 2023, "Mês": 2, "Trimestre": 1, "Vendas": 150},
    {"ID": 3, "Produto": "Tinta Acrílica", "Ano": 2023, "Mês": 3, "Trimestre": 1, "Vendas": 130},
    {"ID": 4, "Produto": "Tinta Acrílica", "Ano": 2023, "Mês": 4, "Trimestre": 2, "Vendas": 180},
    {"ID": 5, "Produto": "Tinta Acrílica", "Ano": 2023, "Mês": 5, "Trimestre": 2, "Vendas": 200},
    {"ID": 6, "Produto": "Tinta Acrílica", "Ano": 2023, "Mês": 6, "Trimestre": 2, "Vendas": 210},
    {"ID": 7, "Produto": "Tinta Acrílica", "Ano": 2023, "Mês": 7, "Trimestre": 3, "Vendas": 190},
    {"ID": 8, "Produto": "Tinta Acrílica", "Ano": 2023, "Mês": 8, "Trimestre": 3, "Vendas": 220},
    {"ID": 9, "Produto": "Tinta Acrílica", "Ano": 2023, "Mês": 9, "Trimestre": 3, "Vendas": 210},
    {"ID": 10, "Produto": "Tinta Acrílica", "Ano": 2023, "Mês": 10, "Trimestre": 4, "Vendas": 250},
    {"ID": 11, "Produto": "Tinta Acrílica", "Ano": 2023, "Mês": 11, "Trimestre": 4, "Vendas": 300},
    {"ID": 12, "Produto": "Tinta Acrílica", "Ano": 2023, "Mês": 12, "Trimestre": 4, "Vendas": 400},
    {"ID": 13, "Produto": "Tinta Esmalte", "Ano": 2023, "Mês": 1, "Trimestre": 1, "Vendas": 80},
    {"ID": 14, "Produto": "Tinta Esmalte", "Ano": 2023, "Mês": 2, "Trimestre": 1, "Vendas": 100},
    {"ID": 15, "Produto": "Tinta Esmalte", "Ano": 2023, "Mês": 3, "Trimestre": 1, "Vendas": 90},
    {"ID": 16, "Produto": "Tinta Esmalte", "Ano": 2023, "Mês": 4, "Trimestre": 2, "Vendas": 120},
    {"ID": 17, "Produto": "Tinta Esmalte", "Ano": 2023, "Mês": 5, "Trimestre": 2, "Vendas": 130},
    {"ID": 18, "Produto": "Tinta Esmalte", "Ano": 2023, "Mês": 6, "Trimestre": 2, "Vendas": 140},
    {"ID": 19, "Produto": "Tinta Esmalte", "Ano": 2023, "Mês": 7, "Trimestre": 3, "Vendas": 150},
    {"ID": 20, "Produto": "Tinta Esmalte", "Ano": 2023, "Mês": 8, "Trimestre": 3, "Vendas": 160},
    {"ID": 21, "Produto": "Tinta Esmalte", "Ano": 2023, "Mês": 9, "Trimestre": 3, "Vendas": 170},
    {"ID": 22, "Produto": "Tinta Esmalte", "Ano": 2023, "Mês": 10, "Trimestre": 4, "Vendas": 180},
    {"ID": 23, "Produto": "Tinta Esmalte", "Ano": 2023, "Mês": 11, "Trimestre": 4, "Vendas": 190},
    {"ID": 24, "Produto": "Tinta Esmalte", "Ano": 2023, "Mês": 12, "Trimestre": 4, "Vendas": 200},
    {"ID": 25, "Produto": "Tinta Látex", "Ano": 2023, "Mês": 1, "Trimestre": 1, "Vendas": 200},
    {"ID": 26, "Produto": "Tinta Látex", "Ano": 2023, "Mês": 2, "Trimestre": 1, "Vendas": 210},
    {"ID": 27, "Produto": "Tinta Látex", "Ano": 2023, "Mês": 3, "Trimestre": 1, "Vendas": 220},
    {"ID": 28, "Produto": "Tinta Látex", "Ano": 2023, "Mês": 4, "Trimestre": 2, "Vendas": 230},
    {"ID": 29, "Produto": "Tinta Látex", "Ano": 2023, "Mês": 5, "Trimestre": 2, "Vendas": 240},
    {"ID": 30, "Produto": "Tinta Látex", "Ano": 2023, "Mês": 6, "Trimestre": 2, "Vendas": 250},
    {"ID": 31, "Produto": "Tinta Látex", "Ano": 2023, "Mês": 7, "Trimestre": 3, "Vendas": 260},
    {"ID": 32, "Produto": "Tinta Látex", "Ano": 2023, "Mês": 8, "Trimestre": 3, "Vendas": 270},
    {"ID": 33, "Produto": "Tinta Látex", "Ano": 2023, "Mês": 9, "Trimestre": 3, "Vendas": 280},
    {"ID": 34, "Produto": "Tinta Látex", "Ano": 2023, "Mês": 10, "Trimestre": 4, "Vendas": 290},
    {"ID": 35, "Produto": "Tinta Látex", "Ano": 2023, "Mês": 11, "Trimestre": 4, "Vendas": 300},
    {"ID": 36, "Produto": "Tinta Látex", "Ano": 2023, "Mês": 12, "Trimestre": 4, "Vendas": 310},
    {"ID": 37, "Produto": "Tinta Spray", "Ano": 2023, "Mês": 1, "Trimestre": 1, "Vendas": 60},
    {"ID": 38, "Produto": "Tinta Spray", "Ano": 2023, "Mês": 2, "Trimestre": 1, "Vendas": 70},
    {"ID": 39, "Produto": "Tinta Spray", "Ano": 2023, "Mês": 3, "Trimestre": 1, "Vendas": 65},
    {"ID": 40, "Produto": "Tinta Spray", "Ano": 2023, "Mês": 4, "Trimestre": 2, "Vendas": 80},
    {"ID": 41, "Produto": "Tinta Spray", "Ano": 2023, "Mês": 5, "Trimestre": 2, "Vendas": 85},
    {"ID": 42, "Produto": "Tinta Spray", "Ano": 2023, "Mês": 6, "Trimestre": 2, "Vendas": 90},
    {"ID": 43, "Produto": "Tinta Spray", "Ano": 2023, "Mês": 7, "Trimestre": 3, "Vendas": 95},
    {"ID": 44, "Produto": "Tinta Spray", "Ano": 2023, "Mês": 8, "Trimestre": 3, "Vendas": 100},
    {"ID": 45, "Produto": "Tinta Spray", "Ano": 2023, "Mês": 9, "Trimestre": 3, "Vendas": 105},
    {"ID": 46, "Produto": "Tinta Spray", "Ano": 2023, "Mês": 10, "Trimestre": 4, "Vendas": 110},
    {"ID": 47, "Produto": "Tinta Spray", "Ano": 2023, "Mês": 11, "Trimestre": 4, "Vendas": 120},
    {"ID": 48, "Produto": "Tinta Spray", "Ano": 2023, "Mês": 12, "Trimestre": 4, "Vendas": 130},
    {"ID": 49, "Produto": "Tinta PVA", "Ano": 2023, "Mês": 1, "Trimestre": 1, "Vendas": 150},
    {"ID": 50, "Produto": "Tinta PVA", "Ano": 2023, "Mês": 2, "Trimestre": 1, "Vendas": 160},
]

print (dados)
# x= mes e y = vendas

x = [item["Mês"] for item in dados]
y = [item["Vendas"] for item in dados]
xquadrado = [item["Mês"] * item["Mês"] for item in dados]
yquadrado = [item["Vendas"]* item["Vendas"]  for item in dados]

somaXQuadrado = sum(xquadrado)
somaYQuadrado = sum(yquadrado)

somaX = sum(x)
somaY = sum(y)

XY = sum([item["Mês"] * item["Vendas"]for item in dados])

qtde = len(dados)


print(xquadrado)
print(yquadrado)

print(somaXQuadrado)
print(somaYQuadrado)
print(sum(x))
print(sum(y))
print(XY)
print(len(dados))

print(qtde)

from typing import Counter
# Formulas
# Calculo do coeficiente angular (m) = (n ∑ (xy) - ∑x∑y) / (n∑x² - (∑x)²)
a = ((qtde * XY) - (somaX * somaY)) / ((qtde * somaXQuadrado) - (somaX * somaX))

print(m)
# Calculo do coeficiente linear (b) b= (∑y - m * ∑x) / n
b = (somaY - a * somaX) / qtde
print(b)

# Equação da reta  YReta = mx +b
YReta = [a * item["Mês"] + b for item in dados]

print(YReta)

produtos = set(item["Produto"] for item in dados)


for mes in [13, 14, 15]:
      y_prev = a * mes + b
      print(f"Mês {mes} → previsão: {y_prev:.2f}")
      print(mes)

produtos = sorted(set([d["Produto"] for d in dados]))

# Função para calcular R², coeficientes e previsão
def calcular_r2(produto, meses_futuros=[13,14,15]):
    vendas_produto = [d for d in dados if d["Produto"] == produto]
    X = np.array([d["Mês"] for d in vendas_produto]).reshape(-1,1)
    y = np.array([d["Vendas"] for d in vendas_produto])

    # Regressão linear
    modelo = LinearRegression()
    modelo.fit(X, y)

    # Coeficientes da reta
    a = modelo.coef_[0]
    b = modelo.intercept_

    # R²
    r2 = modelo.score(X, y)

    # Previsões para meses futuros
    previsoes = {mes: modelo.predict([[mes]])[0] for mes in meses_futuros}

    return a, b, r2, previsoes

# Exemplo:
a, b, r2, previsoes = calcular_r2("Tinta PVA")
print(f"Coeficiente angular (a): {a:.2f}")
print(f"Coeficiente linear (b): {b:.2f}")
print(f"R²: {r2:.4f}")
print("Previsões meses futuros:", {k: f"{v:.2f}" for k,v in previsoes.items()})

# Trimestres: 1 = meses 1-3, 2 = meses 4-6, 3 = meses 7-9, 4 = meses 10-12
trimestres = {1: [1,2,3], 2: [4,5,6], 3: [7,8,9], 4: [10,11,12]}

# Função para calcular previsão e R²
def calcular_prev_r2(produto):
    vendas_produto = [d for d in dados if d["Produto"] == produto]
    X = np.array([d["Mês"] for d in vendas_produto]).reshape(-1,1)
    y = np.array([d["Vendas"] for d in vendas_produto])

    modelo = LinearRegression()
    modelo.fit(X, y)

    y_prev = modelo.predict(X)
    r2 = modelo.score(X, y)

    return y_prev, r2

# Processar todos os produtos
produtos = sorted(set(d["Produto"] for d in dados))

for produto in produtos:
    y_prev, r2 = calcular_prev_r2(produto)
    print(f"\nProduto: {produto} | R²: {r2:.2f}")

    vendas_prev_mensal = {d["Mês"]: y for d, y in zip([d for d in dados if d["Produto"]==produto], y_prev)}

    # Soma por trimestre
    vendas_prev_trimestral = {}
    for t, meses in trimestres.items():
        soma = sum(vendas_prev_mensal[m] for m in meses if m in vendas_prev_mensal)
        vendas_prev_trimestral[t] = soma

    print("Vendas previstas por trimestre:")
    for t, soma in vendas_prev_trimestral.items():
        print(f"Trimestre {t}: {soma:.2f}")

    # Analisar tendência
    valores = list(vendas_prev_trimestral.values())
    if valores == sorted(valores):
        tendencia = "Crescimento"
    elif valores == sorted(valores, reverse=True):
        tendencia = "Queda"
    else:
        tendencia = "Estabilidade / Oscilação"

    print(f"Tendência: {tendencia}")