# -*- coding: utf-8 -*-
"""ML_P1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_jyDN4yPt3t1XVZenuxkMJDoH-zvDTrX
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

# Base de dados
dados = [
    {"ID": 1, "Produto": "Tinta Acrílica", "Ano": 2023, "Mês": 1, "Trimestre": 1, "Vendas": 120},
    {"ID": 2, "Produto": "Tinta Acrílica", "Ano": 2023, "Mês": 2, "Trimestre": 1, "Vendas": 150},
    {"ID": 3, "Produto": "Tinta Acrílica", "Ano": 2023, "Mês": 3, "Trimestre": 1, "Vendas": 130},
    {"ID": 4, "Produto": "Tinta Acrílica", "Ano": 2023, "Mês": 4, "Trimestre": 2, "Vendas": 180},
    {"ID": 5, "Produto": "Tinta Acrílica", "Ano": 2023, "Mês": 5, "Trimestre": 2, "Vendas": 200},
    {"ID": 6, "Produto": "Tinta Acrílica", "Ano": 2023, "Mês": 6, "Trimestre": 2, "Vendas": 210},
    {"ID": 7, "Produto": "Tinta Acrílica", "Ano": 2023, "Mês": 7, "Trimestre": 3, "Vendas": 190},
    {"ID": 8, "Produto": "Tinta Acrílica", "Ano": 2023, "Mês": 8, "Trimestre": 3, "Vendas": 220},
    {"ID": 9, "Produto": "Tinta Acrílica", "Ano": 2023, "Mês": 9, "Trimestre": 3, "Vendas": 210},
    {"ID": 10, "Produto": "Tinta Acrílica", "Ano": 2023, "Mês": 10, "Trimestre": 4, "Vendas": 250},
    {"ID": 11, "Produto": "Tinta Acrílica", "Ano": 2023, "Mês": 11, "Trimestre": 4, "Vendas": 300},
    {"ID": 12, "Produto": "Tinta Acrílica", "Ano": 2023, "Mês": 12, "Trimestre": 4, "Vendas": 400},
    {"ID": 13, "Produto": "Tinta Esmalte", "Ano": 2023, "Mês": 1, "Trimestre": 1, "Vendas": 80},
    {"ID": 14, "Produto": "Tinta Esmalte", "Ano": 2023, "Mês": 2, "Trimestre": 1, "Vendas": 100},
    {"ID": 15, "Produto": "Tinta Esmalte", "Ano": 2023, "Mês": 3, "Trimestre": 1, "Vendas": 90},
    {"ID": 16, "Produto": "Tinta Esmalte", "Ano": 2023, "Mês": 4, "Trimestre": 2, "Vendas": 120},
    {"ID": 17, "Produto": "Tinta Esmalte", "Ano": 2023, "Mês": 5, "Trimestre": 2, "Vendas": 130},
    {"ID": 18, "Produto": "Tinta Esmalte", "Ano": 2023, "Mês": 6, "Trimestre": 2, "Vendas": 140},
    {"ID": 19, "Produto": "Tinta Esmalte", "Ano": 2023, "Mês": 7, "Trimestre": 3, "Vendas": 150},
    {"ID": 20, "Produto": "Tinta Esmalte", "Ano": 2023, "Mês": 8, "Trimestre": 3, "Vendas": 160},
    {"ID": 21, "Produto": "Tinta Esmalte", "Ano": 2023, "Mês": 9, "Trimestre": 3, "Vendas": 170},
    {"ID": 22, "Produto": "Tinta Esmalte", "Ano": 2023, "Mês": 10, "Trimestre": 4, "Vendas": 180},
    {"ID": 23, "Produto": "Tinta Esmalte", "Ano": 2023, "Mês": 11, "Trimestre": 4, "Vendas": 190},
    {"ID": 24, "Produto": "Tinta Esmalte", "Ano": 2023, "Mês": 12, "Trimestre": 4, "Vendas": 200},
    {"ID": 25, "Produto": "Tinta Látex", "Ano": 2023, "Mês": 1, "Trimestre": 1, "Vendas": 200},
    {"ID": 26, "Produto": "Tinta Látex", "Ano": 2023, "Mês": 2, "Trimestre": 1, "Vendas": 210},
    {"ID": 27, "Produto": "Tinta Látex", "Ano": 2023, "Mês": 3, "Trimestre": 1, "Vendas": 220},
    {"ID": 28, "Produto": "Tinta Látex", "Ano": 2023, "Mês": 4, "Trimestre": 2, "Vendas": 230},
    {"ID": 29, "Produto": "Tinta Látex", "Ano": 2023, "Mês": 5, "Trimestre": 2, "Vendas": 240},
    {"ID": 30, "Produto": "Tinta Látex", "Ano": 2023, "Mês": 6, "Trimestre": 2, "Vendas": 250},
    {"ID": 31, "Produto": "Tinta Látex", "Ano": 2023, "Mês": 7, "Trimestre": 3, "Vendas": 260},
    {"ID": 32, "Produto": "Tinta Látex", "Ano": 2023, "Mês": 8, "Trimestre": 3, "Vendas": 270},
    {"ID": 33, "Produto": "Tinta Látex", "Ano": 2023, "Mês": 9, "Trimestre": 3, "Vendas": 280},
    {"ID": 34, "Produto": "Tinta Látex", "Ano": 2023, "Mês": 10, "Trimestre": 4, "Vendas": 290},
    {"ID": 35, "Produto": "Tinta Látex", "Ano": 2023, "Mês": 11, "Trimestre": 4, "Vendas": 300},
    {"ID": 36, "Produto": "Tinta Látex", "Ano": 2023, "Mês": 12, "Trimestre": 4, "Vendas": 310},
    {"ID": 37, "Produto": "Tinta Spray", "Ano": 2023, "Mês": 1, "Trimestre": 1, "Vendas": 60},
    {"ID": 38, "Produto": "Tinta Spray", "Ano": 2023, "Mês": 2, "Trimestre": 1, "Vendas": 70},
    {"ID": 39, "Produto": "Tinta Spray", "Ano": 2023, "Mês": 3, "Trimestre": 1, "Vendas": 65},
    {"ID": 40, "Produto": "Tinta Spray", "Ano": 2023, "Mês": 4, "Trimestre": 2, "Vendas": 80},
    {"ID": 41, "Produto": "Tinta Spray", "Ano": 2023, "Mês": 5, "Trimestre": 2, "Vendas": 85},
    {"ID": 42, "Produto": "Tinta Spray", "Ano": 2023, "Mês": 6, "Trimestre": 2, "Vendas": 90},
    {"ID": 43, "Produto": "Tinta Spray", "Ano": 2023, "Mês": 7, "Trimestre": 3, "Vendas": 95},
    {"ID": 44, "Produto": "Tinta Spray", "Ano": 2023, "Mês": 8, "Trimestre": 3, "Vendas": 100},
    {"ID": 45, "Produto": "Tinta Spray", "Ano": 2023, "Mês": 9, "Trimestre": 3, "Vendas": 105},
    {"ID": 46, "Produto": "Tinta Spray", "Ano": 2023, "Mês": 10, "Trimestre": 4, "Vendas": 110},
    {"ID": 47, "Produto": "Tinta Spray", "Ano": 2023, "Mês": 11, "Trimestre": 4, "Vendas": 120},
    {"ID": 48, "Produto": "Tinta Spray", "Ano": 2023, "Mês": 12, "Trimestre": 4, "Vendas": 130},
    {"ID": 49, "Produto": "Tinta PVA", "Ano": 2023, "Mês": 1, "Trimestre": 1, "Vendas": 150},
    {"ID": 50, "Produto": "Tinta PVA", "Ano": 2023, "Mês": 2, "Trimestre": 1, "Vendas": 160},
]

# Trimestres
trimestres = {1: [1,2,3], 2: [4,5,6], 3: [7,8,9], 4: [10,11,12]}

# Função para calcular previsão e R²
def calcular_prev_r2(produto, meses_futuros=[13,14,15]):
    vendas_produto = [d for d in dados if d["Produto"] == produto]
    X = np.array([d["Mês"] for d in vendas_produto]).reshape(-1,1)
    y = np.array([d["Vendas"] for d in vendas_produto])

    modelo = LinearRegression()
    modelo.fit(X, y)

    y_prev = modelo.predict(X)
    r2 = modelo.score(X, y)

    # Previsões para meses futuros
    previsoes_futuras = {mes: modelo.predict([[mes]])[0] for mes in meses_futuros}

    return y_prev, r2, previsoes_futuras

# Processar todos os produtos e gerar gráficos
tabela_completa = []

produtos = sorted(set(d["Produto"] for d in dados))

for produto in produtos:
    y_prev, r2, previsoes_futuras = calcular_prev_r2(produto)
    vendas_produto = [d for d in dados if d["Produto"] == produto]

    for d, yp in zip(vendas_produto, y_prev):
        tabela_completa.append({
            "Produto": produto,
            "Mês": d["Mês"],
            "Vendas reais": d["Vendas"],
            "Vendas previstas (ŷ)": round(yp, 2),
            "R²": round(r2, 4)
        })

    # Gráfico
    plt.figure(figsize=(8,4))
    plt.plot([d["Mês"] for d in vendas_produto], [d["Vendas"] for d in vendas_produto], 'o-', label="Vendas reais")
    plt.plot([d["Mês"] for d in vendas_produto], y_prev, 's--', label="Vendas previstas")
    plt.title(f"Tendência de vendas - {produto}")
    plt.xlabel("Mês")
    plt.ylabel("Vendas")
    plt.legend()
    plt.grid(True)
    plt.show()

# Criar DataFrame
df = pd.DataFrame(tabela_completa)
print(df)

# Exportar para Excel
df.to_excel("vendas_previstas.xlsx", index=False)