# -*- coding: utf-8 -*-
"""ML_P1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1apeQhZjZq5f3fbF3JGwCbLcanW76hSr7
"""

# -*- coding: utf-8 -*-
"""ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_jyDN4yPt3t1XVZenuxkMJDoH-zvDTrX
"""

import numpy as np
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
import seaborn as sns

# Configurar estilo dos gráficos
plt.style.use('default')
sns.set_palette("husl")

# Base de dados
dados = [
    {"ID": 1, "Produto": "Tinta Acrílica", "Ano": 2023, "Mês": 1, "Trimestre": 1, "Vendas": 120},
    {"ID": 2, "Produto": "Tinta Acrílica", "Ano": 2023, "Mês": 2, "Trimestre": 1, "Vendas": 150},
    {"ID": 3, "Produto": "Tinta Acrílica", "Ano": 2023, "Mês": 3, "Trimestre": 1, "Vendas": 130},
    {"ID": 4, "Produto": "Tinta Acrílica", "Ano": 2023, "Mês": 4, "Trimestre": 2, "Vendas": 180},
    {"ID": 5, "Produto": "Tinta Acrílica", "Ano": 2023, "Mês": 5, "Trimestre": 2, "Vendas": 200},
    {"ID": 6, "Produto": "Tinta Acrílica", "Ano": 2023, "Mês": 6, "Trimestre": 2, "Vendas": 210},
    {"ID": 7, "Produto": "Tinta Acrílica", "Ano": 2023, "Mês": 7, "Trimestre": 3, "Vendas": 190},
    {"ID": 8, "Produto": "Tinta Acrílica", "Ano": 2023, "Mês": 8, "Trimestre": 3, "Vendas": 220},
    {"ID": 9, "Produto": "Tinta Acrílica", "Ano": 2023, "Mês": 9, "Trimestre": 3, "Vendas": 210},
    {"ID": 10, "Produto": "Tinta Acrílica", "Ano": 2023, "Mês": 10, "Trimestre": 4, "Vendas": 250},
    {"ID": 11, "Produto": "Tinta Acrílica", "Ano": 2023, "Mês": 11, "Trimestre": 4, "Vendas": 300},
    {"ID": 12, "Produto": "Tinta Acrílica", "Ano": 2023, "Mês": 12, "Trimestre": 4, "Vendas": 400},
    {"ID": 13, "Produto": "Tinta Esmalte", "Ano": 2023, "Mês": 1, "Trimestre": 1, "Vendas": 80},
    {"ID": 14, "Produto": "Tinta Esmalte", "Ano": 2023, "Mês": 2, "Trimestre": 1, "Vendas": 100},
    {"ID": 15, "Produto": "Tinta Esmalte", "Ano": 2023, "Mês": 3, "Trimestre": 1, "Vendas": 90},
    {"ID": 16, "Produto": "Tinta Esmalte", "Ano": 2023, "Mês": 4, "Trimestre": 2, "Vendas": 120},
    {"ID": 17, "Produto": "Tinta Esmalte", "Ano": 2023, "Mês": 5, "Trimestre": 2, "Vendas": 130},
    {"ID": 18, "Produto": "Tinta Esmalte", "Ano": 2023, "Mês": 6, "Trimestre": 2, "Vendas": 140},
    {"ID": 19, "Produto": "Tinta Esmalte", "Ano": 2023, "Mês": 7, "Trimestre": 3, "Vendas": 150},
    {"ID": 20, "Produto": "Tinta Esmalte", "Ano": 2023, "Mês": 8, "Trimestre": 3, "Vendas": 160},
    {"ID": 21, "Produto": "Tinta Esmalte", "Ano": 2023, "Mês": 9, "Trimestre": 3, "Vendas": 170},
    {"ID": 22, "Produto": "Tinta Esmalte", "Ano": 2023, "Mês": 10, "Trimestre": 4, "Vendas": 180},
    {"ID": 23, "Produto": "Tinta Esmalte", "Ano": 2023, "Mês": 11, "Trimestre": 4, "Vendas": 190},
    {"ID": 24, "Produto": "Tinta Esmalte", "Ano": 2023, "Mês": 12, "Trimestre": 4, "Vendas": 200},
    {"ID": 25, "Produto": "Tinta Látex", "Ano": 2023, "Mês": 1, "Trimestre": 1, "Vendas": 200},
    {"ID": 26, "Produto": "Tinta Látex", "Ano": 2023, "Mês": 2, "Trimestre": 1, "Vendas": 210},
    {"ID": 27, "Produto": "Tinta Látex", "Ano": 2023, "Mês": 3, "Trimestre": 1, "Vendas": 220},
    {"ID": 28, "Produto": "Tinta Látex", "Ano": 2023, "Mês": 4, "Trimestre": 2, "Vendas": 230},
    {"ID": 29, "Produto": "Tinta Látex", "Ano": 2023, "Mês": 5, "Trimestre": 2, "Vendas": 240},
    {"ID": 30, "Produto": "Tinta Látex", "Ano": 2023, "Mês": 6, "Trimestre": 2, "Vendas": 250},
    {"ID": 31, "Produto": "Tinta Látex", "Ano": 2023, "Mês": 7, "Trimestre": 3, "Vendas": 260},
    {"ID": 32, "Produto": "Tinta Látex", "Ano": 2023, "Mês": 8, "Trimestre": 3, "Vendas": 270},
    {"ID": 33, "Produto": "Tinta Látex", "Ano": 2023, "Mês": 9, "Trimestre": 3, "Vendas": 280},
    {"ID": 34, "Produto": "Tinta Látex", "Ano": 2023, "Mês": 10, "Trimestre": 4, "Vendas": 290},
    {"ID": 35, "Produto": "Tinta Látex", "Ano": 2023, "Mês": 11, "Trimestre": 4, "Vendas": 300},
    {"ID": 36, "Produto": "Tinta Látex", "Ano": 2023, "Mês": 12, "Trimestre": 4, "Vendas": 310},
    {"ID": 37, "Produto": "Tinta Spray", "Ano": 2023, "Mês": 1, "Trimestre": 1, "Vendas": 60},
    {"ID": 38, "Produto": "Tinta Spray", "Ano": 2023, "Mês": 2, "Trimestre": 1, "Vendas": 70},
    {"ID": 39, "Produto": "Tinta Spray", "Ano": 2023, "Mês": 3, "Trimestre": 1, "Vendas": 65},
    {"ID": 40, "Produto": "Tinta Spray", "Ano": 2023, "Mês": 4, "Trimestre": 2, "Vendas": 80},
    {"ID": 41, "Produto": "Tinta Spray", "Ano": 2023, "Mês": 5, "Trimestre": 2, "Vendas": 85},
    {"ID": 42, "Produto": "Tinta Spray", "Ano": 2023, "Mês": 6, "Trimestre": 2, "Vendas": 90},
    {"ID": 43, "Produto": "Tinta Spray", "Ano": 2023, "Mês": 7, "Trimestre": 3, "Vendas": 95},
    {"ID": 44, "Produto": "Tinta Spray", "Ano": 2023, "Mês": 8, "Trimestre": 3, "Vendas": 100},
    {"ID": 45, "Produto": "Tinta Spray", "Ano": 2023, "Mês": 9, "Trimestre": 3, "Vendas": 105},
    {"ID": 46, "Produto": "Tinta Spray", "Ano": 2023, "Mês": 10, "Trimestre": 4, "Vendas": 110},
    {"ID": 47, "Produto": "Tinta Spray", "Ano": 2023, "Mês": 11, "Trimestre": 4, "Vendas": 120},
    {"ID": 48, "Produto": "Tinta Spray", "Ano": 2023, "Mês": 12, "Trimestre": 4, "Vendas": 130},
    {"ID": 49, "Produto": "Tinta PVA", "Ano": 2023, "Mês": 1, "Trimestre": 1, "Vendas": 150},
    {"ID": 50, "Produto": "Tinta PVA", "Ano": 2023, "Mês": 2, "Trimestre": 1, "Vendas": 160},
]

print("=== ANÁLISE INICIAL DOS DADOS ===")
print (dados)
# x= mes e y = vendas

x = [item["Mês"] for item in dados]
y = [item["Vendas"] for item in dados]
xquadrado = [item["Mês"] * item["Mês"] for item in dados]
yquadrado = [item["Vendas"]* item["Vendas"]  for item in dados]

somaXQuadrado = sum(xquadrado)
somaYQuadrado = sum(yquadrado)

somaX = sum(x)
somaY = sum(y)

XY = sum([item["Mês"] * item["Vendas"]for item in dados])

qtde = len(dados)


print(xquadrado)
print(yquadrado)

print(somaXQuadrado)
print(somaYQuadrado)
print(sum(x))
print(sum(y))
print(XY)
print(len(dados))

print(qtde)

from typing import Counter
# Formulas
# Calculo do coeficiente angular (m) = (n ∑ (xy) - ∑x∑y) / (n∑x² - (∑x)²)
a = ((qtde * XY) - (somaX * somaY)) / ((qtde * somaXQuadrado) - (somaX * somaX))

print(a)
# Calculo do coeficiente linear (b) b= (∑y - m * ∑x) / n
b = (somaY - a * somaX) / qtde
print(b)

# Equação da reta  YReta = mx +b
YReta = [a * item["Mês"] + b for item in dados]

print(YReta)

produtos = set(item["Produto"] for item in dados)


for mes in [13, 14, 15]:
      y_prev = a * mes + b
      print(f"Mês {mes} → previsão: {y_prev:.2f}")
      print(mes)

print("\n" + "="*50)
print("=== ANÁLISE POR PRODUTO ===")
print("="*50)

produtos = sorted(set([d["Produto"] for d in dados]))

# Função para calcular R², coeficientes e previsão
def calcular_r2(produto, meses_futuros=[13,14,15]):
    vendas_produto = [d for d in dados if d["Produto"] == produto]
    X = np.array([d["Mês"] for d in vendas_produto]).reshape(-1,1)
    y = np.array([d["Vendas"] for d in vendas_produto])

    # Regressão linear
    modelo = LinearRegression()
    modelo.fit(X, y)

    # Coeficientes da reta
    a = modelo.coef_[0]
    b = modelo.intercept_

    # R²
    r2 = modelo.score(X, y)

    # Previsões para meses futuros
    previsoes = {mes: modelo.predict([[mes]])[0] for mes in meses_futuros}

    return a, b, r2, previsoes

# Exemplo:
a, b, r2, previsoes = calcular_r2("Tinta PVA")
print(f"Coeficiente angular (a): {a:.2f}")
print(f"Coeficiente linear (b): {b:.2f}")
print(f"R²: {r2:.4f}")
print("Previsões meses futuros:", {k: f"{v:.2f}" for k,v in previsoes.items()})

# Trimestres: 1 = meses 1-3, 2 = meses 4-6, 3 = meses 7-9, 4 = meses 10-12
trimestres = {1: [1,2,3], 2: [4,5,6], 3: [7,8,9], 4: [10,11,12]}

# Função para calcular previsão e R²
def calcular_prev_r2(produto):
    vendas_produto = [d for d in dados if d["Produto"] == produto]
    X = np.array([d["Mês"] for d in vendas_produto]).reshape(-1,1)
    y = np.array([d["Vendas"] for d in vendas_produto])

    modelo = LinearRegression()
    modelo.fit(X, y)

    y_prev = modelo.predict(X)
    r2 = modelo.score(X, y)

    return y_prev, r2, modelo

# Processar todos os produtos
produtos = sorted(set(d["Produto"] for d in dados))

# Dicionário para armazenar resultados dos modelos
modelos_resultados = {}

for produto in produtos:
    y_prev, r2, modelo = calcular_prev_r2(produto)
    modelos_resultados[produto] = modelo

    print(f"\nProduto: {produto} | R²: {r2:.2f}")

    vendas_prev_mensal = {d["Mês"]: y for d, y in zip([d for d in dados if d["Produto"]==produto], y_prev)}

    # Soma por trimestre
    vendas_prev_trimestral = {}
    for t, meses in trimestres.items():
        soma = sum(vendas_prev_mensal[m] for m in meses if m in vendas_prev_mensal)
        vendas_prev_trimestral[t] = soma

    print("Vendas previstas por trimestre:")
    for t, soma in vendas_prev_trimestral.items():
        print(f"Trimestre {t}: {soma:.2f}")

    # Analisar tendência
    valores = list(vendas_prev_trimestral.values())
    if valores == sorted(valores):
        tendencia = "Crescimento"
    elif valores == sorted(valores, reverse=True):
        tendencia = "Queda"
    else:
        tendencia = "Estabilidade / Oscilação"

    print(f"Tendência: {tendencia}")

print("\n" + "="*50)
print("=== GRÁFICOS ===")
print("="*50)

# Gráfico 1: Vendas reais vs previsão (todos os produtos)
plt.figure(figsize=(14, 8))
for produto in produtos:
    dados_produto = [d for d in dados if d["Produto"] == produto]
    meses = [d["Mês"] for d in dados_produto]
    vendas = [d["Vendas"] for d in dados_produto]

    modelo = modelos_resultados[produto]
    y_prev = modelo.predict(np.array(meses).reshape(-1, 1))

    plt.plot(meses, vendas, 'o-', label=f'{produto} (Real)', linewidth=2, markersize=8)
    plt.plot(meses, y_prev, '--', label=f'{produto} (Previsão)', linewidth=2, alpha=0.7)

plt.xlabel('Mês', fontsize=12)
plt.ylabel('Vendas', fontsize=12)
plt.title('Vendas Reais vs Previsão por Produto', fontsize=14, fontweight='bold')
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

# Gráfico 2: Comparativo de vendas por trimestre (todos os produtos)
plt.figure(figsize=(12, 6))
produtos_lista = []
trimestres_lista = []
vendas_lista = []

for produto in produtos:
    dados_produto = [d for d in dados if d["Produto"] == produto]
    for trimestre in [1, 2, 3, 4]:
        vendas_trimestre = sum([d["Vendas"] for d in dados_produto if d["Trimestre"] == trimestre])
        produtos_lista.append(produto)
        trimestres_lista.append(f'T{trimestre}')
        vendas_lista.append(vendas_trimestre)

# Criar DataFrame para seaborn
import pandas as pd
df_vendas = pd.DataFrame({
    'Produto': produtos_lista,
    'Trimestre': trimestres_lista,
    'Vendas': vendas_lista
})

# Gráfico de barras agrupadas
plt.figure(figsize=(14, 8))
sns.barplot(data=df_vendas, x='Produto', y='Vendas', hue='Trimestre')
plt.title('Vendas por Trimestre e Produto', fontsize=14, fontweight='bold')
plt.xlabel('Produto', fontsize=12)
plt.ylabel('Vendas Totais', fontsize=12)
plt.legend(title='Trimestre', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.xticks(rotation=45, ha='right')
plt.grid(True, alpha=0.3, axis='y')
plt.tight_layout()
plt.show()

# Gráfico 3: Previsões para meses futuros
plt.figure(figsize=(12, 6))
meses_futuros = [13, 14, 15]

for produto in produtos:
    modelo = modelos_resultados[produto]
    previsoes = modelo.predict(np.array(meses_futuros).reshape(-1, 1))
    plt.plot(meses_futuros, previsoes, 'o-', label=produto, linewidth=2, markersize=8)

plt.xlabel('Mês (2024)', fontsize=12)
plt.ylabel('Previsão de Vendas', fontsize=12)
plt.title('Previsão de Vendas para os Primeiros Meses de 2024', fontsize=14, fontweight='bold')
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.grid(True, alpha=0.3)
plt.xticks(meses_futuros, ['Jan/24', 'Fev/24', 'Mar/24'])
plt.tight_layout()
plt.show()

# Gráfico 4: Comparativo R² dos modelos
plt.figure(figsize=(10, 6))
r2_valores = []
for produto in produtos:
    dados_produto = [d for d in dados if d["Produto"] == produto]
    X = np.array([d["Mês"] for d in dados_produto]).reshape(-1,1)
    y = np.array([d["Vendas"] for d in dados_produto])
    modelo = LinearRegression()
    modelo.fit(X, y)
    r2 = modelo.score(X, y)
    r2_valores.append(r2)

colors = ['green' if r2 > 0.8 else 'orange' if r2 > 0.6 else 'red' for r2 in r2_valores]
plt.bar(produtos, r2_valores, color=colors)
plt.xlabel('Produto', fontsize=12)
plt.ylabel('R² (Coeficiente de Determinação)', fontsize=12)
plt.title('Qualidade do Modelo por Produto', fontsize=14, fontweight='bold')
plt.xticks(rotation=45, ha='right')
plt.axhline(y=0.8, color='green', linestyle='--', alpha=0.5, label='Bom (R² > 0.8)')
plt.axhline(y=0.6, color='orange', linestyle='--', alpha=0.5, label='Regular (R² > 0.6)')
plt.legend()
plt.grid(True, alpha=0.3, axis='y')
plt.tight_layout()
plt.show()

# Gráfico 5: Distribuição de vendas por produto (Boxplot)
plt.figure(figsize=(12, 6))
dados_para_boxplot = []
labels = []

for produto in produtos:
    vendas_produto = [d["Vendas"] for d in dados if d["Produto"] == produto]
    dados_para_boxplot.append(vendas_produto)
    labels.append(produto)

bp = plt.boxplot(dados_para_boxplot, labels=labels, patch_artist=True)
for box in bp['boxes']:
    box.set_facecolor('lightblue')
    box.set_alpha(0.7)

plt.xlabel('Produto', fontsize=12)
plt.ylabel('Vendas', fontsize=12)
plt.title('Distribuição de Vendas por Produto', fontsize=14, fontweight='bold')
plt.xticks(rotation=45, ha='right')
plt.grid(True, alpha=0.3, axis='y')
plt.tight_layout()
plt.show()

# Gráfico 6: Evolução mensal detalhada por produto (Subplots)
fig, axes = plt.subplots(2, 3, figsize=(15, 10))
axes = axes.flatten()

for idx, produto in enumerate(produtos):
    dados_produto = [d for d in dados if d["Produto"] == produto]
    meses = [d["Mês"] for d in dados_produto]
    vendas = [d["Vendas"] for d in dados_produto]

    modelo = modelos_resultados[produto]
    y_prev = modelo.predict(np.array(meses).reshape(-1, 1))
    r2 = modelo.score(np.array(meses).reshape(-1, 1), np.array(vendas))

    axes[idx].plot(meses, vendas, 'o-', label='Vendas Reais', linewidth=2, markersize=6)
    axes[idx].plot(meses, y_prev, '--', label=f'Previsão (R²={r2:.2f})', linewidth=2)
    axes[idx].set_title(f'{produto}', fontsize=12, fontweight='bold')
    axes[idx].set_xlabel('Mês')
    axes[idx].set_ylabel('Vendas')
    axes[idx].legend()
    axes[idx].grid(True, alpha=0.3)

# Remover subplot vazio se houver
if len(produtos) < 6:
    for idx in range(len(produtos), 6):
        fig.delaxes(axes[idx])

plt.suptitle('Análise Mensal Detalhada por Produto', fontsize=16, fontweight='bold')
plt.tight_layout()
plt.show()

print("\n" + "="*50)
print("=== RESUMO FINAL ===")
print("="*50)

# Gerar resumo final com previsões
for produto in produtos:
    modelo = modelos_resultados[produto]
    dados_produto = [d for d in dados if d["Produto"] == produto]
    X = np.array([d["Mês"] for d in dados_produto]).reshape(-1,1)
    y = np.array([d["Vendas"] for d in dados_produto])
    r2 = modelo.score(X, y)

    print(f"\n📊 {produto}")
    print(f"   • Coeficiente angular: {modelo.coef_[0]:.2f}")
    print(f"   • Coeficiente linear: {modelo.intercept_:.2f}")
    print(f"   • R²: {r2:.4f}")
    print(f"   • Previsões 2024:")
    for mes, valor in zip(['Jan', 'Fev', 'Mar'], modelo.predict([[13], [14], [15]])):
        print(f"     - {mes}: {valor:.2f}")

print("\n✅ Análise concluída com sucesso!")